# Generated by Django 3.1.12 on 2021-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20180522_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='joindate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
