# Generated by Django 3.1.12 on 2021-09-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_item_joindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
    ]
