# Generated by Django 2.2.24 on 2021-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='joindate',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.CharField(choices=[('cat1', 'Cat1'), ('cat2', 'Cat2'), ('cat3', 'Cat3'), ('cat4', 'Cat4'), ('cat5', 'Cat5')], default='green', max_length=6),
        ),
    ]
